services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    restart: unless-stopped
